apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-lb 
spec:
  template:
    metadata:
      name: my-nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod
      
---

apiVersion: v1 
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
  - targetPort: 80
    port: 80
  selector:
    app: nginx-pod