apiVersion: v1
kind: Service
metadata:
  name: dynamic-service
  namespace: dynamic
spec:
  selector:
    app: dynamic-application
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
