apiVersion: v1
kind: Pod
metadata:
  name: timezone-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: timezone
      mountPath: /etc/localtime  
      subPath: Asia/Kolkata
  volumes:
  - name: timezone
    hostPath:
      path: /usr/share/zoneinfo