apiVersion: v1

kind: Pod

metadata:
  name: pending-pod
  
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "30"]
      resources:
        requests:
          memory: "10Gi"
          cpu: "13000m"