apiVersion: v1
kind: Pod
metadata:
  name: prestop-example
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      lifecycle:
        preStop:
          exec:
            command: ["/bin/sh", "-c", "echo 'Nginx is shutting down...!!!' > /usr/share/nginx/html/prestop.txt && sleep 10"]